# Generated by Django 3.2.3 on 2021-05-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='gif',
        ),
        migrations.AddField(
            model_name='gif',
            name='category',
            field=models.ManyToManyField(to='gifs.Category'),
        ),
    ]
